[build]
  publish = "build"
  command = "npm install --force && CI=false GENERATE_SOURCEMAP=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  SKIP_PREFLIGHT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200