[build]
  publish = "build"
  command = "npm install --force && CI=false GENERATE_SOURCEMAP=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  SKIP_PREFLIGHT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  SECRETS_SCAN_ENABLED = "false"
  REACT_APP_SENTRY_DSN = "https://35ab290d698fd51da71555c2c1d17983@o4509847852089344.ingest.us.sentry.io/4509847853989888"
  REACT_APP_SENTRY_ENVIRONMENT = "production"
  REACT_APP_GA_MEASUREMENT_ID = "G-3T4FZFWM9J"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200