[build]
  publish = "build"
  command = "npm install --force && CI=false GENERATE_SOURCEMAP=false npm run build"
  functions = "netlify/functions"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_GOOGLE_MAPS_API_KEY"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Default SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Function proxying
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"